### ISSUE TITLE
Update user docs to show password length

### ISSUE THREAD

**Issue by hepabolu** [podfeet/docsify-user-docs-xkpasswd#3] opened 2024-10-01 16:08 UTC
The min and max password length is now visible in the statistics section. This means the screenshots in the statistics section of this user guide need to be adjusted, and maybe you could add a paragraph on the password length.

**Comment by podfeet** [comment] 2024-10-23 14:48
I'm on it

**Comment by podfeet** [comment] 2024-11-18 19:09
I've updated the screenshots to show the min/max password length. I have not added a paragraph on the password length as that's a duplicate of issue #4 which I've explained must be addressed by @bbusschots

**Closed as completed by podfeet** 2024-11-18 19:09 UTC
